.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH ddcui 1 "13 June 2020"
.\" Please adjust this date whenever revising the manpage.
.\"

.SH NAME
ddcui \- GUI for ddcutil
.SH SYNOPSIS



.\" ALT USING .SY .OP
.\" .SY
.\" .OP \-abcde
.\" .OP \-b busno
.\" .OP \-d|--display dispno
.\" command command-arguments
.\" .YS


.SH DESCRIPTION
\fBddcui\fP is a graphical user interface for \fBddcutil\fP.
For documentation, see http://www.ddcutil.com/ddcui.main.



\fBddcutil\fP communicates with monitors implementing MCCS (Monitor Control Command Set) using the DDC/CI protocol on the I2C bus.  
Normally, the video driver for the monitor exposes the I2C bus as devices named /dev/i2c-n.  
Alternatively, \fBddcutil\fP can communicate with USB connected monitors implementing the USB Monitor Control Class Specification.

The Monitor Control Command Set describes a collection of Virtual Control Panel (VCP) features that a monitor can implement.
Each feature is identified using a single byte.  For example, feature x10 is the brightness control. 

In general, the monitor settings that can be controlled by \fBddcutil\fP are a superset of what can be changed using the buttons
on a monitor and its on screen display.  The specific capabilities vary from monitor to monitor.

A particular use case for \fBddcutil\fP is as part of color profile management.  
Monitor calibration is relative to the monitor color settings currently in effect, e.g. red gain.  
\fBddcutil\fP allows color related settings to be saved at the time a monitor is calibrated, 
and then restored when the calibration is applied.

Another common use case is to switch the monitor input source.

This man page includes only abbreviated documentation of trace and other program diagnostic facilities.

For extended documentation, use the "--help" option, and see http://www.ddcutil.com. 

.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics, 
.\" respectively.


.\" .B ddcutil
.\" .I command 
.\" .R [
.\" .I command-arguments
.\" .R ] [
.\" .I options
.\" .R ]



.SH OPTIONS

For documentation on command line options, see http:\\www.ddcutil.com/ddcui_options, or use the
\fB--help\fP option. 


.SH AUTHOR
Sanford Rockowitz (rockowitz at minsoft dot com)
.br
Copyright 2019\-2020 Sanford Rockowitz


