#! /usr/bin/sh

cd /shared/playproj/ddcui/icons/work
 cp ../cinema_display_blue.ico          ddcui.ico
 cp ../cinema_display_blue_multires.ico ddcui_multires.ico
 cp ../cinema_display_blue.png          ddcui.png
 icotool -x ddcui_multires.ico
 rm -rf icons
 mkdir -p hicolor/16x16/apps
 mkdir -p hicolor/32x32/apps
 mkdir -p hicolor/48x48/apps
 mkdir -p hicolor/128x128/apps

 cp ddcui_multires_1_128x128x32.png hicolor/128x128/apps/ddcui.png
 cp ddcui_multires_2_48x48x32.png   hicolor/48x48/apps/ddcui.png
 cp ddcui_multires_3_32x32x32.png   hicolor/32x32/apps/ddcui.png
 cp ddcui_multires_4_16x16x32.png   hicolor/16x16/apps/ddcui.png

 mkdir -p hicolor/scalable/apps
 convert ddcui.png  hicolor/scalable/apps/ddcui.svg




